# Generated by Django 3.1.6 on 2021-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_auto_20210212_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ImageField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], upload_to='profile_image/user_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=200),
        ),
    ]
