# Generated by Django 3.1.6 on 2021-02-12 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating_app', '0003_auto_20210212_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(null=True, to='dating_app.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
