# Generated by Django 3.1.6 on 2021-02-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_auto_20210212_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
