# Generated by Django 3.1.6 on 2021-02-12 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating_app', '0006_remove_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
